### ISSUE TITLE
pse編譯

### ISSUE THREAD

**Issue by Sslience** [li10141110/PSENet-tf2#3]
tf2框架比1好用，但是我嘗試了很多方法對pse編譯，依然報錯，作者可以下編譯好的.io文件麽，謝謝！

**Comment by lzh37** [comment]
直接用其他人编译生成的.so文件好像还是会出问题，最好自己编译。你可以把编译时的报错贴出来看看吗？

**Comment by li10141110** [comment]
建议先用python 版本 pypse
