### ISSUE TITLE
和你知乎上说的不一样啊

### ISSUE THREAD

**Issue by 975150313** [li10141110/PSENet-tf2#4]
另外整合了结合最新Resnest，resnet，regnet，mobilenetV2，mobilenetV3等网络的Unet网络，拿走就用。。。。，
说好的regnet unet呢

**Comment by Ri-Yue-Shui-Hua** [comment]
训练说明中的CUDA_VISIBLE_DEVICES=0 python train_ic15.py
 train_ic15.py文件不存在。

**Comment by li10141110** [comment]
目前还在更新，Resnest，resnet，regnet，mobilenetV2，mobilenetV3都已经经过测试
